[02/Sep/2018 07:34:08] "GET / HTTP/1.1" 200 14411
[02/Sep/2018 07:35:19] code 400, message Bad request syntax ('\x00\xa9\x02\x00\x0c\x00QUERY_STRING\x00\x00\x0e\x00REQUEST_METHOD\x03\x00GET\x0c\x00CONTENT_TYPE\x00\x00\x0e\x00CONTENT_LENGTH\x00\x00\x0b\x00REQUEST_URI\x01\x00/\t\x00PATH_INFO\x01\x00/\r\x00DOCUMENT_ROOT\x15\x00/usr/share/nginx/html\x0f\x00SERVER_PROTOCOL\x08\x00HTTP/1.0\x0e\x00REQUEST_SCHEME\x04\x00http\x0b\x00REMOTE_ADDR\r\x0039.108.122.78\x0b\x00REMOTE_PORT\x05\x0058160\x0b\x00SERVER_PORT\x04\x008000\x0b\x00SERVER_NAME\r\x0039.108.122.78\t\x00HTTP_HOST\x12\x0039.108.122.78:8000\x0f\x00HTTP_CONNECTION\x05\x00close\x1e\x00HTTP_UPGRADE_INSECURE_REQUESTS\x01\x001\x0f\x00HTTP_USER_AGENTn\x00Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36\x0b\x00HTTP_ACCEPTU\x00text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8\x14\x00HTTP_ACCEPT_ENCODING\x11\x00gzip, deflate, br\x14\x00HTTP_ACCEPT_LANGUAGE\x0e\x00zh-CN,zh;q=0.9')
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/log.py", line 192, in format
    return super(ServerFormatter, self).format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 476, in format
    raise e
UnicodeDecodeError: 'ascii' codec can't decode byte 0xa9 in position 2: ordinal not in range(128)
Logged from file basehttp.py, line 131
[02/Sep/2018 07:35:19] "GET / HTTP/1.1" 200 14411
[02/Sep/2018 07:36:36] code 400, message Bad request syntax ('\x00\xa9\x02\x00\x0c\x00QUERY_STRING\x00\x00\x0e\x00REQUEST_METHOD\x03\x00GET\x0c\x00CONTENT_TYPE\x00\x00\x0e\x00CONTENT_LENGTH\x00\x00\x0b\x00REQUEST_URI\x01\x00/\t\x00PATH_INFO\x01\x00/\r\x00DOCUMENT_ROOT\x15\x00/usr/share/nginx/html\x0f\x00SERVER_PROTOCOL\x08\x00HTTP/1.0\x0e\x00REQUEST_SCHEME\x04\x00http\x0b\x00REMOTE_ADDR\r\x0039.108.122.78\x0b\x00REMOTE_PORT\x05\x0058164\x0b\x00SERVER_PORT\x04\x008000\x0b\x00SERVER_NAME\r\x0039.108.122.78\t\x00HTTP_HOST\x12\x0039.108.122.78:8000\x0f\x00HTTP_CONNECTION\x05\x00close\x1e\x00HTTP_UPGRADE_INSECURE_REQUESTS\x01\x001\x0f\x00HTTP_USER_AGENTn\x00Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36\x0b\x00HTTP_ACCEPTU\x00text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8\x14\x00HTTP_ACCEPT_ENCODING\x11\x00gzip, deflate, br\x14\x00HTTP_ACCEPT_LANGUAGE\x0e\x00zh-CN,zh;q=0.9')
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/log.py", line 192, in format
    return super(ServerFormatter, self).format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 476, in format
    raise e
UnicodeDecodeError: 'ascii' codec can't decode byte 0xa9 in position 2: ordinal not in range(128)
Logged from file basehttp.py, line 131
[02/Sep/2018 07:37:37] code 400, message Bad request syntax ("\x00\x92\x02\x00\x0c\x00QUERY_STRING\x00\x00\x0e\x00REQUEST_METHOD\x03\x00GET\x0c\x00CONTENT_TYPE\x00\x00\x0e\x00CONTENT_LENGTH\x00\x00\x0b\x00REQUEST_URI\x0c\x00/favicon.ico\t\x00PATH_INFO\x0c\x00/favicon.ico\r\x00DOCUMENT_ROOT\x15\x00/usr/share/nginx/html\x0f\x00SERVER_PROTOCOL\x08\x00HTTP/1.0\x0e\x00REQUEST_SCHEME\x04\x00http\x0b\x00REMOTE_ADDR\r\x0039.108.122.78\x0b\x00REMOTE_PORT\x05\x0058168\x0b\x00SERVER_PORT\x04\x008000\x0b\x00SERVER_NAME\r\x0039.108.122.78\t\x00HTTP_HOST\x12\x0039.108.122.78:8000\x0f\x00HTTP_CONNECTION\x05\x00close\x0f\x00HTTP_USER_AGENTn\x00Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36\x0b\x00HTTP_ACCEPT'\x00image/webp,image/apng,image/*,*/*;q=0.8\x0c\x00HTTP_REFERER\x14\x00https://ellie.ac.cn/\x14\x00HTTP_ACCEPT_ENCODING\x11\x00gzip, deflate, br\x14\x00HTTP_ACCEPT_LANGUAGE\x0e\x00zh-CN,zh;q=0.9")
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/log.py", line 192, in format
    return super(ServerFormatter, self).format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 476, in format
    raise e
UnicodeDecodeError: 'ascii' codec can't decode byte 0x92 in position 2: ordinal not in range(128)
Logged from file basehttp.py, line 131
[02/Sep/2018 07:37:49] code 400, message Bad request syntax ('\x00\xeb\x01\x00\x0c\x00QUERY_STRING\x00\x00\x0e\x00REQUEST_METHOD\x03\x00GET\x0c\x00CONTENT_TYPE\x00\x00\x0e\x00CONTENT_LENGTH\x00\x00\x0b\x00REQUEST_URI\x01\x00/\t\x00PATH_INFO\x01\x00/\r\x00DOCUMENT_ROOT\x15\x00/usr/share/nginx/html\x0f\x00SERVER_PROTOCOL\x08\x00HTTP/1.0\x0e\x00REQUEST_SCHEME\x04\x00http\x0b\x00REMOTE_ADDR\r\x0039.108.122.78\x0b\x00REMOTE_PORT\x05\x0058176\x0b\x00SERVER_PORT\x04\x008000\x0b\x00SERVER_NAME\r\x0039.108.122.78\t\x00HTTP_HOST\x12\x0039.108.122.78:8000\x0f\x00HTTP_CONNECTION\x05\x00close\x0b\x00HTTP_ACCEPT\x03\x00*/*\x14\x00HTTP_ACCEPT_LANGUAGE\x05\x00zh-cn\x0c\x00HTTP_REFERER\x15\x00https://39.108.122.78\x0f\x00HTTP_USER_AGENT2\x00Mozilla/4.0 (compatible; MSIE 9.0; Windows NT 6.1)')
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/log.py", line 192, in format
    return super(ServerFormatter, self).format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 476, in format
    raise e
UnicodeDecodeError: 'ascii' codec can't decode byte 0xeb in position 2: ordinal not in range(128)
Logged from file basehttp.py, line 131
[02/Sep/2018 07:37:49] code 400, message Bad request syntax ('\x00\xeb\x01\x00\x0c\x00QUERY_STRING\x00\x00\x0e\x00REQUEST_METHOD\x03\x00GET\x0c\x00CONTENT_TYPE\x00\x00\x0e\x00CONTENT_LENGTH\x00\x00\x0b\x00REQUEST_URI\x01\x00/\t\x00PATH_INFO\x01\x00/\r\x00DOCUMENT_ROOT\x15\x00/usr/share/nginx/html\x0f\x00SERVER_PROTOCOL\x08\x00HTTP/1.0\x0e\x00REQUEST_SCHEME\x04\x00http\x0b\x00REMOTE_ADDR\r\x0039.108.122.78\x0b\x00REMOTE_PORT\x05\x0058172\x0b\x00SERVER_PORT\x04\x008000\x0b\x00SERVER_NAME\r\x0039.108.122.78\t\x00HTTP_HOST\x12\x0039.108.122.78:8000\x0f\x00HTTP_CONNECTION\x05\x00close\x0b\x00HTTP_ACCEPT\x03\x00*/*\x14\x00HTTP_ACCEPT_LANGUAGE\x05\x00zh-cn\x0c\x00HTTP_REFERER\x15\x00https://39.108.122.78\x0f\x00HTTP_USER_AGENT2\x00Mozilla/4.0 (compatible; MSIE 9.0; Windows NT 6.1)')
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/log.py", line 192, in format
    return super(ServerFormatter, self).format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 476, in format
    raise e
UnicodeDecodeError: 'ascii' codec can't decode byte 0xeb in position 2: ordinal not in range(128)
Logged from file basehttp.py, line 131
[02/Sep/2018 07:40:41] code 400, message Bad request syntax ('\x00\xc8\x02\x00\x0c\x00QUERY_STRING\x00\x00\x0e\x00REQUEST_METHOD\x03\x00GET\x0c\x00CONTENT_TYPE\x00\x00\x0e\x00CONTENT_LENGTH\x00\x00\x0b\x00REQUEST_URI\x01\x00/\t\x00PATH_INFO\x01\x00/\r\x00DOCUMENT_ROOT\x15\x00/usr/share/nginx/html\x0f\x00SERVER_PROTOCOL\x08\x00HTTP/1.0\x0e\x00REQUEST_SCHEME\x04\x00http\x0b\x00REMOTE_ADDR\r\x0039.108.122.78\x0b\x00REMOTE_PORT\x05\x0058180\x0b\x00SERVER_PORT\x04\x008000\x0b\x00SERVER_NAME\r\x0039.108.122.78\t\x00HTTP_HOST\x12\x0039.108.122.78:8000\x0f\x00HTTP_CONNECTION\x05\x00close\x12\x00HTTP_CACHE_CONTROL\t\x00max-age=0\x1e\x00HTTP_UPGRADE_INSECURE_REQUESTS\x01\x001\x0f\x00HTTP_USER_AGENTn\x00Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36\x0b\x00HTTP_ACCEPTU\x00text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8\x14\x00HTTP_ACCEPT_ENCODING\x11\x00gzip, deflate, br\x14\x00HTTP_ACCEPT_LANGUAGE\x0e\x00zh-CN,zh;q=0.9')
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/log.py", line 192, in format
    return super(ServerFormatter, self).format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 476, in format
    raise e
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc8 in position 2: ordinal not in range(128)
Logged from file basehttp.py, line 131
[02/Sep/2018 07:41:42] code 400, message Bad request syntax ("\x00\x92\x02\x00\x0c\x00QUERY_STRING\x00\x00\x0e\x00REQUEST_METHOD\x03\x00GET\x0c\x00CONTENT_TYPE\x00\x00\x0e\x00CONTENT_LENGTH\x00\x00\x0b\x00REQUEST_URI\x0c\x00/favicon.ico\t\x00PATH_INFO\x0c\x00/favicon.ico\r\x00DOCUMENT_ROOT\x15\x00/usr/share/nginx/html\x0f\x00SERVER_PROTOCOL\x08\x00HTTP/1.0\x0e\x00REQUEST_SCHEME\x04\x00http\x0b\x00REMOTE_ADDR\r\x0039.108.122.78\x0b\x00REMOTE_PORT\x05\x0058184\x0b\x00SERVER_PORT\x04\x008000\x0b\x00SERVER_NAME\r\x0039.108.122.78\t\x00HTTP_HOST\x12\x0039.108.122.78:8000\x0f\x00HTTP_CONNECTION\x05\x00close\x0f\x00HTTP_USER_AGENTn\x00Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36\x0b\x00HTTP_ACCEPT'\x00image/webp,image/apng,image/*,*/*;q=0.8\x0c\x00HTTP_REFERER\x14\x00https://ellie.ac.cn/\x14\x00HTTP_ACCEPT_ENCODING\x11\x00gzip, deflate, br\x14\x00HTTP_ACCEPT_LANGUAGE\x0e\x00zh-CN,zh;q=0.9")
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/log.py", line 192, in format
    return super(ServerFormatter, self).format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 476, in format
    raise e
UnicodeDecodeError: 'ascii' codec can't decode byte 0x92 in position 2: ordinal not in range(128)
Logged from file basehttp.py, line 131
[02/Sep/2018 07:47:28] code 400, message Bad request syntax ('\x00\xc8\x02\x00\x0c\x00QUERY_STRING\x00\x00\x0e\x00REQUEST_METHOD\x03\x00GET\x0c\x00CONTENT_TYPE\x00\x00\x0e\x00CONTENT_LENGTH\x00\x00\x0b\x00REQUEST_URI\x01\x00/\t\x00PATH_INFO\x01\x00/\r\x00DOCUMENT_ROOT\x15\x00/usr/share/nginx/html\x0f\x00SERVER_PROTOCOL\x08\x00HTTP/1.0\x0e\x00REQUEST_SCHEME\x04\x00http\x0b\x00REMOTE_ADDR\r\x0039.108.122.78\x0b\x00REMOTE_PORT\x05\x0058188\x0b\x00SERVER_PORT\x04\x008000\x0b\x00SERVER_NAME\r\x0039.108.122.78\t\x00HTTP_HOST\x12\x0039.108.122.78:8000\x0f\x00HTTP_CONNECTION\x05\x00close\x12\x00HTTP_CACHE_CONTROL\t\x00max-age=0\x1e\x00HTTP_UPGRADE_INSECURE_REQUESTS\x01\x001\x0f\x00HTTP_USER_AGENTn\x00Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36\x0b\x00HTTP_ACCEPTU\x00text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8\x14\x00HTTP_ACCEPT_ENCODING\x11\x00gzip, deflate, br\x14\x00HTTP_ACCEPT_LANGUAGE\x0e\x00zh-CN,zh;q=0.9')
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/log.py", line 192, in format
    return super(ServerFormatter, self).format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 476, in format
    raise e
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc8 in position 2: ordinal not in range(128)
Logged from file basehttp.py, line 131
[02/Sep/2018 07:48:28] code 400, message Bad request syntax ("\x00\x92\x02\x00\x0c\x00QUERY_STRING\x00\x00\x0e\x00REQUEST_METHOD\x03\x00GET\x0c\x00CONTENT_TYPE\x00\x00\x0e\x00CONTENT_LENGTH\x00\x00\x0b\x00REQUEST_URI\x0c\x00/favicon.ico\t\x00PATH_INFO\x0c\x00/favicon.ico\r\x00DOCUMENT_ROOT\x15\x00/usr/share/nginx/html\x0f\x00SERVER_PROTOCOL\x08\x00HTTP/1.0\x0e\x00REQUEST_SCHEME\x04\x00http\x0b\x00REMOTE_ADDR\r\x0039.108.122.78\x0b\x00REMOTE_PORT\x05\x0058192\x0b\x00SERVER_PORT\x04\x008000\x0b\x00SERVER_NAME\r\x0039.108.122.78\t\x00HTTP_HOST\x12\x0039.108.122.78:8000\x0f\x00HTTP_CONNECTION\x05\x00close\x0f\x00HTTP_USER_AGENTn\x00Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36\x0b\x00HTTP_ACCEPT'\x00image/webp,image/apng,image/*,*/*;q=0.8\x0c\x00HTTP_REFERER\x14\x00https://ellie.ac.cn/\x14\x00HTTP_ACCEPT_ENCODING\x11\x00gzip, deflate, br\x14\x00HTTP_ACCEPT_LANGUAGE\x0e\x00zh-CN,zh;q=0.9")
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/log.py", line 192, in format
    return super(ServerFormatter, self).format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 476, in format
    raise e
UnicodeDecodeError: 'ascii' codec can't decode byte 0x92 in position 2: ordinal not in range(128)
Logged from file basehttp.py, line 131
[02/Sep/2018 07:50:14] code 400, message Bad request syntax ('\x00\xc8\x02\x00\x0c\x00QUERY_STRING\x00\x00\x0e\x00REQUEST_METHOD\x03\x00GET\x0c\x00CONTENT_TYPE\x00\x00\x0e\x00CONTENT_LENGTH\x00\x00\x0b\x00REQUEST_URI\x01\x00/\t\x00PATH_INFO\x01\x00/\r\x00DOCUMENT_ROOT\x15\x00/usr/share/nginx/html\x0f\x00SERVER_PROTOCOL\x08\x00HTTP/1.0\x0e\x00REQUEST_SCHEME\x04\x00http\x0b\x00REMOTE_ADDR\r\x0039.108.122.78\x0b\x00REMOTE_PORT\x05\x0058196\x0b\x00SERVER_PORT\x04\x008000\x0b\x00SERVER_NAME\r\x0039.108.122.78\t\x00HTTP_HOST\x12\x0039.108.122.78:8000\x0f\x00HTTP_CONNECTION\x05\x00close\x12\x00HTTP_CACHE_CONTROL\t\x00max-age=0\x1e\x00HTTP_UPGRADE_INSECURE_REQUESTS\x01\x001\x0f\x00HTTP_USER_AGENTn\x00Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36\x0b\x00HTTP_ACCEPTU\x00text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8\x14\x00HTTP_ACCEPT_ENCODING\x11\x00gzip, deflate, br\x14\x00HTTP_ACCEPT_LANGUAGE\x0e\x00zh-CN,zh;q=0.9')
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/log.py", line 192, in format
    return super(ServerFormatter, self).format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 476, in format
    raise e
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc8 in position 2: ordinal not in range(128)
Logged from file basehttp.py, line 131
Performing system checks...

System check identified no issues (0 silenced).
September 02, 2018 - 07:51:39
Django version 1.10.8, using settings 'mysite.settings'
Starting development server at http://0.0.0.0:8001/
Quit the server with CONTROL-C.
[02/Sep/2018 07:54:23] code 400, message Bad request syntax ('\x00\xc8\x02\x00\x0c\x00QUERY_STRING\x00\x00\x0e\x00REQUEST_METHOD\x03\x00GET\x0c\x00CONTENT_TYPE\x00\x00\x0e\x00CONTENT_LENGTH\x00\x00\x0b\x00REQUEST_URI\x01\x00/\t\x00PATH_INFO\x01\x00/\r\x00DOCUMENT_ROOT\x15\x00/usr/share/nginx/html\x0f\x00SERVER_PROTOCOL\x08\x00HTTP/1.0\x0e\x00REQUEST_SCHEME\x04\x00http\x0b\x00REMOTE_ADDR\r\x0039.108.122.78\x0b\x00REMOTE_PORT\x05\x0058204\x0b\x00SERVER_PORT\x04\x008000\x0b\x00SERVER_NAME\r\x0039.108.122.78\t\x00HTTP_HOST\x12\x0039.108.122.78:8000\x0f\x00HTTP_CONNECTION\x05\x00close\x12\x00HTTP_CACHE_CONTROL\t\x00max-age=0\x1e\x00HTTP_UPGRADE_INSECURE_REQUESTS\x01\x001\x0f\x00HTTP_USER_AGENTn\x00Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36\x0b\x00HTTP_ACCEPTU\x00text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8\x14\x00HTTP_ACCEPT_ENCODING\x11\x00gzip, deflate, br\x14\x00HTTP_ACCEPT_LANGUAGE\x0e\x00zh-CN,zh;q=0.9')
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/log.py", line 192, in format
    return super(ServerFormatter, self).format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 476, in format
    raise e
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc8 in position 2: ordinal not in range(128)
Logged from file basehttp.py, line 131
[02/Sep/2018 07:55:23] code 400, message Bad request syntax ("\x00\x92\x02\x00\x0c\x00QUERY_STRING\x00\x00\x0e\x00REQUEST_METHOD\x03\x00GET\x0c\x00CONTENT_TYPE\x00\x00\x0e\x00CONTENT_LENGTH\x00\x00\x0b\x00REQUEST_URI\x0c\x00/favicon.ico\t\x00PATH_INFO\x0c\x00/favicon.ico\r\x00DOCUMENT_ROOT\x15\x00/usr/share/nginx/html\x0f\x00SERVER_PROTOCOL\x08\x00HTTP/1.0\x0e\x00REQUEST_SCHEME\x04\x00http\x0b\x00REMOTE_ADDR\r\x0039.108.122.78\x0b\x00REMOTE_PORT\x05\x0058208\x0b\x00SERVER_PORT\x04\x008000\x0b\x00SERVER_NAME\r\x0039.108.122.78\t\x00HTTP_HOST\x12\x0039.108.122.78:8000\x0f\x00HTTP_CONNECTION\x05\x00close\x0f\x00HTTP_USER_AGENTn\x00Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36\x0b\x00HTTP_ACCEPT'\x00image/webp,image/apng,image/*,*/*;q=0.8\x0c\x00HTTP_REFERER\x14\x00https://ellie.ac.cn/\x14\x00HTTP_ACCEPT_ENCODING\x11\x00gzip, deflate, br\x14\x00HTTP_ACCEPT_LANGUAGE\x0e\x00zh-CN,zh;q=0.9")
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/log.py", line 192, in format
    return super(ServerFormatter, self).format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 476, in format
    raise e
UnicodeDecodeError: 'ascii' codec can't decode byte 0x92 in position 2: ordinal not in range(128)
Logged from file basehttp.py, line 131
[02/Sep/2018 07:56:13] code 400, message Bad request syntax ('\x00\xc8\x02\x00\x0c\x00QUERY_STRING\x00\x00\x0e\x00REQUEST_METHOD\x03\x00GET\x0c\x00CONTENT_TYPE\x00\x00\x0e\x00CONTENT_LENGTH\x00\x00\x0b\x00REQUEST_URI\x01\x00/\t\x00PATH_INFO\x01\x00/\r\x00DOCUMENT_ROOT\x15\x00/usr/share/nginx/html\x0f\x00SERVER_PROTOCOL\x08\x00HTTP/1.0\x0e\x00REQUEST_SCHEME\x04\x00http\x0b\x00REMOTE_ADDR\r\x0039.108.122.78\x0b\x00REMOTE_PORT\x05\x0058212\x0b\x00SERVER_PORT\x04\x008000\x0b\x00SERVER_NAME\r\x0039.108.122.78\t\x00HTTP_HOST\x12\x0039.108.122.78:8000\x0f\x00HTTP_CONNECTION\x05\x00close\x12\x00HTTP_CACHE_CONTROL\t\x00max-age=0\x1e\x00HTTP_UPGRADE_INSECURE_REQUESTS\x01\x001\x0f\x00HTTP_USER_AGENTn\x00Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36\x0b\x00HTTP_ACCEPTU\x00text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8\x14\x00HTTP_ACCEPT_ENCODING\x11\x00gzip, deflate, br\x14\x00HTTP_ACCEPT_LANGUAGE\x0e\x00zh-CN,zh;q=0.9')
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/log.py", line 192, in format
    return super(ServerFormatter, self).format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 476, in format
    raise e
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc8 in position 2: ordinal not in range(128)
Logged from file basehttp.py, line 131
[02/Sep/2018 07:56:23] "GET / HTTP/1.1" 200 14411
[02/Sep/2018 08:01:13] code 400, message Bad request syntax ('\x00\xa9\x02\x00\x0c\x00QUERY_STRING\x00\x00\x0e\x00REQUEST_METHOD\x03\x00GET\x0c\x00CONTENT_TYPE\x00\x00\x0e\x00CONTENT_LENGTH\x00\x00\x0b\x00REQUEST_URI\x01\x00/\t\x00PATH_INFO\x01\x00/\r\x00DOCUMENT_ROOT\x15\x00/usr/share/nginx/html\x0f\x00SERVER_PROTOCOL\x08\x00HTTP/1.0\x0e\x00REQUEST_SCHEME\x04\x00http\x0b\x00REMOTE_ADDR\r\x0039.108.122.78\x0b\x00REMOTE_PORT\x05\x0058216\x0b\x00SERVER_PORT\x04\x008000\x0b\x00SERVER_NAME\r\x0039.108.122.78\t\x00HTTP_HOST\x12\x0039.108.122.78:8000\x0f\x00HTTP_CONNECTION\x05\x00close\x1e\x00HTTP_UPGRADE_INSECURE_REQUESTS\x01\x001\x0f\x00HTTP_USER_AGENTn\x00Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36\x0b\x00HTTP_ACCEPTU\x00text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8\x14\x00HTTP_ACCEPT_ENCODING\x11\x00gzip, deflate, br\x14\x00HTTP_ACCEPT_LANGUAGE\x0e\x00zh-CN,zh;q=0.9')
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/log.py", line 192, in format
    return super(ServerFormatter, self).format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 476, in format
    raise e
UnicodeDecodeError: 'ascii' codec can't decode byte 0xa9 in position 2: ordinal not in range(128)
Logged from file basehttp.py, line 131
[02/Sep/2018 08:02:34] code 400, message Bad request syntax ('\x00\xa9\x02\x00\x0c\x00QUERY_STRING\x00\x00\x0e\x00REQUEST_METHOD\x03\x00GET\x0c\x00CONTENT_TYPE\x00\x00\x0e\x00CONTENT_LENGTH\x00\x00\x0b\x00REQUEST_URI\x01\x00/\t\x00PATH_INFO\x01\x00/\r\x00DOCUMENT_ROOT\x15\x00/usr/share/nginx/html\x0f\x00SERVER_PROTOCOL\x08\x00HTTP/1.0\x0e\x00REQUEST_SCHEME\x04\x00http\x0b\x00REMOTE_ADDR\r\x0039.108.122.78\x0b\x00REMOTE_PORT\x05\x0058220\x0b\x00SERVER_PORT\x04\x008000\x0b\x00SERVER_NAME\r\x0039.108.122.78\t\x00HTTP_HOST\x12\x0039.108.122.78:8000\x0f\x00HTTP_CONNECTION\x05\x00close\x1e\x00HTTP_UPGRADE_INSECURE_REQUESTS\x01\x001\x0f\x00HTTP_USER_AGENTn\x00Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36\x0b\x00HTTP_ACCEPTU\x00text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8\x14\x00HTTP_ACCEPT_ENCODING\x11\x00gzip, deflate, br\x14\x00HTTP_ACCEPT_LANGUAGE\x0e\x00zh-CN,zh;q=0.9')
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/log.py", line 192, in format
    return super(ServerFormatter, self).format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 476, in format
    raise e
UnicodeDecodeError: 'ascii' codec can't decode byte 0xa9 in position 2: ordinal not in range(128)
Logged from file basehttp.py, line 131
[02/Sep/2018 08:03:35] code 400, message Bad request syntax ("\x00\x92\x02\x00\x0c\x00QUERY_STRING\x00\x00\x0e\x00REQUEST_METHOD\x03\x00GET\x0c\x00CONTENT_TYPE\x00\x00\x0e\x00CONTENT_LENGTH\x00\x00\x0b\x00REQUEST_URI\x0c\x00/favicon.ico\t\x00PATH_INFO\x0c\x00/favicon.ico\r\x00DOCUMENT_ROOT\x15\x00/usr/share/nginx/html\x0f\x00SERVER_PROTOCOL\x08\x00HTTP/1.0\x0e\x00REQUEST_SCHEME\x04\x00http\x0b\x00REMOTE_ADDR\r\x0039.108.122.78\x0b\x00REMOTE_PORT\x05\x0058224\x0b\x00SERVER_PORT\x04\x008000\x0b\x00SERVER_NAME\r\x0039.108.122.78\t\x00HTTP_HOST\x12\x0039.108.122.78:8000\x0f\x00HTTP_CONNECTION\x05\x00close\x0f\x00HTTP_USER_AGENTn\x00Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36\x0b\x00HTTP_ACCEPT'\x00image/webp,image/apng,image/*,*/*;q=0.8\x0c\x00HTTP_REFERER\x14\x00https://ellie.ac.cn/\x14\x00HTTP_ACCEPT_ENCODING\x11\x00gzip, deflate, br\x14\x00HTTP_ACCEPT_LANGUAGE\x0e\x00zh-CN,zh;q=0.9")
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/log.py", line 192, in format
    return super(ServerFormatter, self).format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 476, in format
    raise e
UnicodeDecodeError: 'ascii' codec can't decode byte 0x92 in position 2: ordinal not in range(128)
Logged from file basehttp.py, line 131
[02/Sep/2018 08:05:02] code 400, message Bad request version ('\xd3jx\xe4\xae]\xf5R\x80\x9b\x164\x00"**\x13\x03\x13\x01\x13\x02\xcc\xa9\xcc\xa8\xc0+\xc0/\xc0,\xc00\xc0\x13\xc0\x14\x00\x9c\x00\x9d\x00/\x005\x00')
[02/Sep/2018 08:05:02] You're accessing the development server over HTTPS, but it only supports HTTP.

[02/Sep/2018 08:05:02] code 400, message Bad request version ('ht\x1c\xa9j\x07\x92WUX\x11\xb2\x1c\xdb\xbegq\x00\x00\x1c\xaa\xaa\xcc\xa9\xcc\xa8\xc0+\xc0/\xc0,\xc00\xc0\x13\xc0\x14\x00\x9c\x00\x9d\x00/\x005\x00')
[02/Sep/2018 08:05:02] You're accessing the development server over HTTPS, but it only supports HTTP.

[02/Sep/2018 08:05:21] "GET / HTTP/1.1" 200 14411
[02/Sep/2018 08:07:25] "GET / HTTP/1.1" 200 14411
[02/Sep/2018 08:07:38] "GET / HTTP/1.0" 200 14411
Performing system checks...

System check identified no issues (0 silenced).
November 06, 2018 - 06:46:14
Django version 1.10.8, using settings 'mysite.settings'
Starting development server at http://0.0.0.0:8001/
Quit the server with CONTROL-C.
*** Starting uWSGI 2.0.17 (64bit) on [Tue Nov  6 14:55:27 2018] ***
compiled with version: 5.4.0 20160609 on 12 March 2018 02:22:44
os: Linux-4.4.0-85-generic #108-Ubuntu SMP Mon Jul 3 17:23:59 UTC 2017
nodename: iZwz9d3a5jshh18akapij2Z
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /home/ellie/mysecondblog/mysite
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 7857
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on :8001 fd 4
spawned uWSGI http 1 (pid: 26156)
uwsgi socket 0 bound to TCP address 127.0.0.1:39942 (port auto-assigned) fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 2.7.12 (default, Dec  4 2017, 14:50:18)  [GCC 5.4.0 20160609]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x13daa00
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 72904 bytes (71 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x13daa00 pid: 26155 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 26155, cores: 1)
Not Found: /manager/html
[pid: 26155|app: 0|req: 1/1] 123.249.0.134 () {30 vars in 462 bytes} [Tue Nov  6 06:55:49 2018] GET /manager/html => generated 3429 bytes in 81 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
Not Found: /http:/wujieliulan.com/
[pid: 26155|app: 0|req: 2/2] 60.177.178.220 () {32 vars in 478 bytes} [Tue Nov  6 07:51:13 2018] GET http://wujieliulan.com/ => generated 1668 bytes in 4 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
Not Found: /http:/www.minghui.org/
[pid: 26155|app: 0|req: 3/3] 60.177.178.220 () {32 vars in 478 bytes} [Tue Nov  6 07:51:13 2018] GET http://www.minghui.org/ => generated 1668 bytes in 3 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
Not Found: /http:/www.epochtimes.com/
[pid: 26155|app: 0|req: 4/4] 60.177.178.220 () {32 vars in 487 bytes} [Tue Nov  6 07:51:13 2018] GET http://www.epochtimes.com/ => generated 1680 bytes in 5 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
Not Found: /http:/www.boxun.com/
[pid: 26155|app: 0|req: 5/5] 60.177.178.220 () {32 vars in 472 bytes} [Tue Nov  6 07:51:13 2018] GET http://www.boxun.com/ => generated 1660 bytes in 4 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
Not Found: /http:/www.bing.com/
[pid: 26155|app: 0|req: 6/6] 60.177.178.220 () {32 vars in 469 bytes} [Tue Nov  6 07:51:13 2018] GET http://www.bing.com/ => generated 1656 bytes in 3 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
Not Found: /http:/www.baidu.com/
[pid: 26155|app: 0|req: 7/7] 60.177.178.220 () {32 vars in 472 bytes} [Tue Nov  6 07:51:13 2018] GET http://www.baidu.com/ => generated 1660 bytes in 6 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
Not Found: /www.voanews.com:443
[pid: 26155|app: 0|req: 8/8] 60.177.178.220 () {22 vars in 275 bytes} [Tue Nov  6 07:51:13 2018] CONNECT www.voanews.com:443 => generated 1674 bytes in 3 msecs (HTTP/1.0 404) 2 headers in 80 bytes (1 switches on core 0)
Not Found: /http:/www.123cha.com/
[pid: 26155|app: 0|req: 9/9] 60.177.178.220 () {32 vars in 475 bytes} [Tue Nov  6 07:51:25 2018] GET http://www.123cha.com/ => generated 1664 bytes in 3 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
[pid: 26155|app: 0|req: 10/10] 47.100.64.9 () {22 vars in 232 bytes} [Tue Nov  6 18:53:31 2018] GET / => generated 14411 bytes in 157 msecs (HTTP/1.0 200) 2 headers in 88 bytes (1 switches on core 0)
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
[pid: 26155|app: 0|req: 11/11] 80.82.78.50 () {28 vars in 425 bytes} [Tue Nov  6 22:07:00 2018] GET http://www.baidu.com/cache/global/img/gs.gif => generated 1729 bytes in 3 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
[pid: 26155|app: 0|req: 12/12] 118.31.244.58 () {22 vars in 234 bytes} [Tue Nov  6 22:27:01 2018] GET / => generated 14411 bytes in 5 msecs (HTTP/1.0 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 26155|app: 0|req: 13/13] 39.107.14.208 () {22 vars in 234 bytes} [Wed Nov  7 16:14:50 2018] GET / => generated 14411 bytes in 6 msecs (HTTP/1.0 200) 2 headers in 88 bytes (1 switches on core 0)
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
[pid: 26155|app: 0|req: 14/14] 80.82.78.50 () {28 vars in 425 bytes} [Wed Nov  7 20:34:47 2018] GET http://www.baidu.com/cache/global/img/gs.gif => generated 1729 bytes in 4 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
[pid: 26155|app: 0|req: 15/15] 218.102.243.88 () {22 vars in 235 bytes} [Thu Nov  8 15:26:43 2018] GET / => generated 14411 bytes in 5 msecs (HTTP/1.0 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 26155|app: 0|req: 16/16] 47.97.16.76 () {22 vars in 231 bytes} [Thu Nov  8 16:14:39 2018] GET / => generated 14411 bytes in 6 msecs (HTTP/1.0 200) 2 headers in 88 bytes (1 switches on core 0)
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
[pid: 26155|app: 0|req: 17/17] 80.82.78.50 () {28 vars in 423 bytes} [Thu Nov  8 18:58:42 2018] GET http://www.baidu.com/cache/global/img/gs.gif => generated 1729 bytes in 3 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
[pid: 26155|app: 0|req: 18/18] 98.172.185.17 () {22 vars in 234 bytes} [Thu Nov  8 20:38:09 2018] GET / => generated 14411 bytes in 7 msecs (HTTP/1.0 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 26155|app: 0|req: 19/19] 139.162.79.87 () {30 vars in 347 bytes} [Fri Nov  9 02:11:11 2018] GET / => generated 14411 bytes in 4 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[uwsgi-http key:  client_addr: 5.39.222.3 client_port: 26369] hr_read(): Connection reset by peer [plugins/http/http.c line 917]
[pid: 26155|app: 0|req: 20/20] 94.102.49.190 () {30 vars in 489 bytes} [Fri Nov  9 12:58:06 2018] GET / => generated 14411 bytes in 6 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
Not Found: /favicon.ico
[pid: 26155|app: 0|req: 21/21] 94.102.49.190 () {32 vars in 412 bytes} [Fri Nov  9 12:58:09 2018] GET /favicon.ico => generated 3426 bytes in 5 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
[pid: 26155|app: 0|req: 22/22] 80.82.78.50 () {28 vars in 425 bytes} [Fri Nov  9 17:24:55 2018] GET http://www.baidu.com/cache/global/img/gs.gif => generated 1729 bytes in 4 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
[pid: 26155|app: 0|req: 23/23] 47.97.16.76 () {22 vars in 232 bytes} [Fri Nov  9 19:47:47 2018] GET / => generated 14411 bytes in 5 msecs (HTTP/1.0 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 26155|app: 0|req: 24/24] 120.78.225.124 () {22 vars in 235 bytes} [Fri Nov  9 23:16:35 2018] GET / => generated 14411 bytes in 5 msecs (HTTP/1.0 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 26155|app: 0|req: 25/25] 125.64.94.200 () {22 vars in 234 bytes} [Sat Nov 10 15:14:12 2018] GET / => generated 14411 bytes in 5 msecs (HTTP/1.0 200) 2 headers in 88 bytes (1 switches on core 0)
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
[pid: 26155|app: 0|req: 26/26] 80.82.78.50 () {28 vars in 424 bytes} [Sat Nov 10 15:58:22 2018] GET http://www.baidu.com/cache/global/img/gs.gif => generated 1729 bytes in 3 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
[pid: 26155|app: 0|req: 27/27] 106.15.52.246 () {22 vars in 233 bytes} [Sat Nov 10 16:20:58 2018] GET / => generated 14411 bytes in 5 msecs (HTTP/1.0 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 26155|app: 0|req: 28/28] 106.15.53.214 () {22 vars in 234 bytes} [Sat Nov 10 17:14:43 2018] GET / => generated 14411 bytes in 5 msecs (HTTP/1.0 200) 2 headers in 88 bytes (1 switches on core 0)
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
[pid: 26155|app: 0|req: 29/29] 80.82.78.50 () {28 vars in 425 bytes} [Sun Nov 11 14:25:30 2018] GET http://www.baidu.com/cache/global/img/gs.gif => generated 1729 bytes in 6 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
[pid: 26155|app: 0|req: 30/30] 106.15.52.246 () {22 vars in 234 bytes} [Sun Nov 11 16:50:31 2018] GET / => generated 14411 bytes in 6 msecs (HTTP/1.0 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 26155|app: 0|req: 31/31] 47.95.28.143 () {22 vars in 233 bytes} [Sun Nov 11 23:05:28 2018] GET / => generated 14411 bytes in 5 msecs (HTTP/1.0 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 26155|app: 0|req: 32/32] 173.20.100.29 () {22 vars in 234 bytes} [Mon Nov 12 05:00:42 2018] GET / => generated 14411 bytes in 5 msecs (HTTP/1.0 200) 2 headers in 88 bytes (1 switches on core 0)
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
[pid: 26155|app: 0|req: 33/33] 80.82.78.50 () {28 vars in 425 bytes} [Mon Nov 12 12:52:16 2018] GET http://www.baidu.com/cache/global/img/gs.gif => generated 1729 bytes in 3 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
[pid: 26155|app: 0|req: 34/34] 119.23.139.140 () {22 vars in 235 bytes} [Mon Nov 12 19:15:29 2018] GET / => generated 14411 bytes in 6 msecs (HTTP/1.0 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 26155|app: 0|req: 35/35] 47.97.21.76 () {22 vars in 232 bytes} [Mon Nov 12 20:10:00 2018] GET / => generated 14411 bytes in 7 msecs (HTTP/1.0 200) 2 headers in 88 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.17 (64bit) on [Tue Nov 13 23:19:44 2018] ***
compiled with version: 5.4.0 20160609 on 12 March 2018 02:22:44
os: Linux-4.4.0-85-generic #108-Ubuntu SMP Mon Jul 3 17:23:59 UTC 2017
nodename: iZwz9d3a5jshh18akapij2Z
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /home/ellie/ellix-blog/mysecondblog/mysite
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 7857
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on :8001 fd 4
spawned uWSGI http 1 (pid: 18519)
uwsgi socket 0 bound to TCP address 127.0.0.1:42198 (port auto-assigned) fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 2.7.12 (default, Dec  4 2017, 14:50:18)  [GCC 5.4.0 20160609]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0xd7ba30
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 72904 bytes (71 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0xd7ba30 pid: 18518 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 18518, cores: 1)
*** Starting uWSGI 2.0.17 (64bit) on [Tue Nov 13 23:20:55 2018] ***
compiled with version: 5.4.0 20160609 on 12 March 2018 02:22:44
os: Linux-4.4.0-85-generic #108-Ubuntu SMP Mon Jul 3 17:23:59 UTC 2017
nodename: iZwz9d3a5jshh18akapij2Z
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /home/ellie/ellix-blog/mysecondblog/mysite
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 7857
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on :8001 fd 4
spawned uWSGI http 1 (pid: 18528)
uwsgi socket 0 bound to TCP address 127.0.0.1:36691 (port auto-assigned) fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 2.7.12 (default, Dec  4 2017, 14:50:18)  [GCC 5.4.0 20160609]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1e9ba30
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 72904 bytes (71 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x1e9ba30 pid: 18527 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 18527, cores: 1)
[pid: 18527|app: 0|req: 1/1] 66.42.59.81 () {36 vars in 618 bytes} [Tue Nov 13 15:21:25 2018] GET / => generated 14411 bytes in 47 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
Not Found: /static/css/layers.min.css
[pid: 18527|app: 0|req: 2/2] 66.42.59.81 () {36 vars in 628 bytes} [Tue Nov 13 15:21:26 2018] GET /static/css/layers.min.css => generated 3466 bytes in 6 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
Not Found: /static/js/beetle.js
[pid: 18527|app: 0|req: 3/3] 66.42.59.81 () {36 vars in 601 bytes} [Tue Nov 13 15:21:26 2018] GET /static/js/beetle.js => generated 3448 bytes in 6 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
Not Found: /static/css/font-awesome.min.css
[pid: 18527|app: 0|req: 4/4] 66.42.59.81 () {36 vars in 640 bytes} [Tue Nov 13 15:21:26 2018] GET /static/css/font-awesome.min.css => generated 3484 bytes in 4 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
Not Found: /static/js/plugins.js
[pid: 18527|app: 0|req: 5/5] 66.42.59.81 () {36 vars in 603 bytes} [Tue Nov 13 15:21:26 2018] GET /static/js/plugins.js => generated 3451 bytes in 5 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
Not Found: /static/style.css
[pid: 18527|app: 0|req: 6/6] 66.42.59.81 () {36 vars in 610 bytes} [Tue Nov 13 15:21:27 2018] GET /static/style.css => generated 3439 bytes in 7 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
[pid: 18527|app: 0|req: 7/7] 66.42.59.81 () {36 vars in 655 bytes} [Tue Nov 13 15:21:28 2018] GET /media/uploadImage/%E7%BF%BC%E5%B9%B4%E4%BB%A3%E8%AE%B0.jpg => generated 171268 bytes in 5 msecs via sendfile() (HTTP/1.1 200) 4 headers in 144 bytes (0 switches on core 0)
[pid: 18527|app: 0|req: 8/8] 66.42.59.81 () {36 vars in 615 bytes} [Tue Nov 13 15:21:28 2018] GET /media/uploadImage/img2.jpg => generated 69647 bytes in 0 msecs via sendfile() (HTTP/1.1 200) 4 headers in 143 bytes (0 switches on core 0)
[pid: 18527|app: 0|req: 9/9] 66.42.59.81 () {36 vars in 615 bytes} [Tue Nov 13 15:21:28 2018] GET /media/uploadImage/img3.jpg => generated 22789 bytes in 0 msecs via sendfile() (HTTP/1.1 200) 4 headers in 143 bytes (0 switches on core 0)
Not Found: /static/img/feather.jpg
[pid: 18527|app: 0|req: 10/10] 66.42.59.81 () {36 vars in 607 bytes} [Tue Nov 13 15:21:28 2018] GET /static/img/feather.jpg => generated 3457 bytes in 5 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
Not Found: /static/js/plugins.js
[pid: 18527|app: 0|req: 11/11] 66.42.59.81 () {36 vars in 603 bytes} [Tue Nov 13 15:21:28 2018] GET /static/js/plugins.js => generated 3451 bytes in 6 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
Not Found: /static/js/beetle.js
[pid: 18527|app: 0|req: 12/12] 66.42.59.81 () {36 vars in 601 bytes} [Tue Nov 13 15:21:30 2018] GET /static/js/beetle.js => generated 3448 bytes in 6 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
Not Found: /static/favicon.ico
[pid: 18527|app: 0|req: 13/13] 66.42.59.81 () {34 vars in 619 bytes} [Tue Nov 13 15:21:31 2018] GET /static/favicon.ico => generated 3445 bytes in 8 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
Not Found: /static/img/apple-touch-icon-152x152.png
[pid: 18527|app: 0|req: 14/14] 66.42.59.81 () {34 vars in 661 bytes} [Tue Nov 13 15:21:32 2018] GET /static/img/apple-touch-icon-152x152.png => generated 3508 bytes in 5 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
Internal Server Error: /personal_1/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./mysite/view.py", line 42, in article_personal
    article_ = models.Article_personal.objects.get(id=id)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 385, in get
    self.model._meta.object_name
DoesNotExist: Article_personal matching query does not exist.
[pid: 18527|app: 0|req: 15/15] 66.42.59.81 () {38 vars in 680 bytes} [Tue Nov 13 15:21:48 2018] GET /personal_1/ => generated 66306 bytes in 176 msecs (HTTP/1.1 500) 3 headers in 106 bytes (1 switches on core 0)
Not Found: /favicon.ico
[pid: 18527|app: 0|req: 16/16] 66.42.59.81 () {34 vars in 605 bytes} [Tue Nov 13 15:21:52 2018] GET /favicon.ico => generated 3424 bytes in 6 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
Not Found: /static/favicon.ico
[pid: 18527|app: 0|req: 17/17] 66.42.59.81 () {34 vars in 619 bytes} [Tue Nov 13 15:21:56 2018] GET /static/favicon.ico => generated 3445 bytes in 6 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
Not Found: /static/img/apple-touch-icon-152x152.png
[pid: 18527|app: 0|req: 18/18] 66.42.59.81 () {34 vars in 661 bytes} [Tue Nov 13 15:21:57 2018] GET /static/img/apple-touch-icon-152x152.png => generated 3508 bytes in 6 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.17 (64bit) on [Tue Nov 13 23:29:57 2018] ***
compiled with version: 5.4.0 20160609 on 12 March 2018 02:22:44
os: Linux-4.4.0-85-generic #108-Ubuntu SMP Mon Jul 3 17:23:59 UTC 2017
nodename: iZwz9d3a5jshh18akapij2Z
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /home/ellie/ellix-blog/mysecondblog/mysite
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 7857
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on :8001 fd 4
spawned uWSGI http 1 (pid: 18799)
uwsgi socket 0 bound to TCP address 127.0.0.1:42711 (port auto-assigned) fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 2.7.12 (default, Dec  4 2017, 14:50:18)  [GCC 5.4.0 20160609]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1232a30
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 72904 bytes (71 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x1232a30 pid: 18798 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 18798, cores: 1)
[pid: 18798|app: 0|req: 1/1] 47.94.39.226 () {22 vars in 233 bytes} [Tue Nov 13 16:31:46 2018] GET / => generated 14411 bytes in 26 msecs (HTTP/1.0 200) 2 headers in 88 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.17 (64bit) on [Wed Nov 14 00:35:45 2018] ***
compiled with version: 5.4.0 20160609 on 12 March 2018 02:22:44
os: Linux-4.4.0-85-generic #108-Ubuntu SMP Mon Jul 3 17:23:59 UTC 2017
nodename: iZwz9d3a5jshh18akapij2Z
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /home/ellie/ellix-blog/mysecondblog/mysite
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 7857
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on :8001 fd 4
spawned uWSGI http 1 (pid: 18915)
uwsgi socket 0 bound to TCP address 127.0.0.1:41259 (port auto-assigned) fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 2.7.12 (default, Dec  4 2017, 14:50:18)  [GCC 5.4.0 20160609]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0xe79a10
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 72904 bytes (71 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0xe79a10 pid: 18914 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 18914, cores: 1)
[pid: 18914|app: 0|req: 1/1] 112.96.195.4 () {36 vars in 619 bytes} [Tue Nov 13 16:40:16 2018] GET / => generated 14411 bytes in 26 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
Not Found: /static/css/layers.min.css
[pid: 18914|app: 0|req: 2/2] 112.96.195.4 () {36 vars in 629 bytes} [Tue Nov 13 16:40:16 2018] GET /static/css/layers.min.css => generated 3466 bytes in 6 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
Not Found: /static/css/font-awesome.min.css
[pid: 18914|app: 0|req: 3/3] 112.96.195.4 () {36 vars in 641 bytes} [Tue Nov 13 16:40:16 2018] GET /static/css/font-awesome.min.css => generated 3484 bytes in 5 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
Not Found: /static/style.css
[pid: 18914|app: 0|req: 4/4] 112.96.195.4 () {36 vars in 611 bytes} [Tue Nov 13 16:40:16 2018] GET /static/style.css => generated 3439 bytes in 5 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
Not Found: /static/js/plugins.js
[pid: 18914|app: 0|req: 5/5] 112.96.195.4 () {36 vars in 604 bytes} [Tue Nov 13 16:40:17 2018] GET /static/js/plugins.js => generated 3451 bytes in 8 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
Not Found: /static/js/beetle.js
[pid: 18914|app: 0|req: 6/6] 112.96.195.4 () {36 vars in 602 bytes} [Tue Nov 13 16:40:17 2018] GET /static/js/beetle.js => generated 3448 bytes in 8 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
[pid: 18914|app: 0|req: 7/7] 112.96.195.4 () {38 vars in 711 bytes} [Tue Nov 13 16:40:17 2018] GET /media/uploadImage/%E7%BF%BC%E5%B9%B4%E4%BB%A3%E8%AE%B0.jpg => generated 0 bytes in 1 msecs (HTTP/1.1 304) 1 headers in 58 bytes (0 switches on core 0)
[pid: 18914|app: 0|req: 8/8] 112.96.195.4 () {38 vars in 671 bytes} [Tue Nov 13 16:40:17 2018] GET /media/uploadImage/img2.jpg => generated 0 bytes in 1 msecs (HTTP/1.1 304) 1 headers in 58 bytes (0 switches on core 0)
[pid: 18914|app: 0|req: 9/9] 112.96.195.4 () {38 vars in 671 bytes} [Tue Nov 13 16:40:17 2018] GET /media/uploadImage/img3.jpg => generated 0 bytes in 1 msecs (HTTP/1.1 304) 1 headers in 58 bytes (0 switches on core 0)
Not Found: /static/img/feather.jpg
[pid: 18914|app: 0|req: 10/10] 112.96.195.4 () {36 vars in 608 bytes} [Tue Nov 13 16:40:17 2018] GET /static/img/feather.jpg => generated 3457 bytes in 5 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
Not Found: /static/img/apple-touch-icon-152x152.png
[pid: 18914|app: 0|req: 11/11] 112.96.195.4 () {34 vars in 662 bytes} [Tue Nov 13 16:40:18 2018] GET /static/img/apple-touch-icon-152x152.png => generated 3508 bytes in 5 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
Not Found: /static/favicon.ico
[pid: 18914|app: 0|req: 12/12] 112.96.195.4 () {34 vars in 620 bytes} [Tue Nov 13 16:40:18 2018] GET /static/favicon.ico => generated 3445 bytes in 6 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
[pid: 18914|app: 0|req: 13/13] 47.52.210.105 () {22 vars in 234 bytes} [Tue Nov 13 17:45:15 2018] GET / => generated 14411 bytes in 7 msecs (HTTP/1.0 200) 2 headers in 88 bytes (1 switches on core 0)
[pid: 18914|app: 0|req: 14/14] 101.132.107.246 () {30 vars in 456 bytes} [Wed Nov 14 02:16:39 2018] GET / => generated 14411 bytes in 5 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 0)
[uwsgi-http key:  client_addr: 190.64.79.122 client_port: 21212] hr_read(): Connection reset by peer [plugins/http/http.c line 917]
